#!/bin/bash

#  cat << EOF > $output_file: This starts a here document. Everything between EOF and the second EOF is treated as input to cat, 
#  and is written to index.html


# Define the output HTML file
output_file="index.html"

# Generate the HTML content using a here document
cat << EOF > $output_file
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple HTML Page</title>
</head>
<body>
    <h1>Welcome to Zude Communication</h1>
    <p>This is a simple HTML file generated by a bash script.</p>
</body>
</html>

EOF

# Confirm that the HTML file was created successfully
echo "HTML file '$output_file' has been generated."

